"""Catálogo oficial del Anexo Transaccional Simplificado (ATS) del SRI.

Transcrito literalmente desde el archivo oficial "Catálogo Anexo Transaccional
Simplificado ATS.xls" (hoja "TABLAS REFERENCIALES"). Primera transcripción el
13-09-2026 (ficha listada como actualizada el 03-03-2026). Recontrastado el
23-09-2026 contra una descarga fresca del mismo archivo (ficha listada como
actualizada el 06-08-2026, ya posterior a la primera transcripción): se
encontraron y corrigieron 24 códigos de país faltantes (incluye Argentina,
Bolivia, Brasil, Canadá y Colombia, ausentes desde la primera transcripción) y
el código de comprobante 374 (Nota de débito operadora transporte / socio),
también faltante. El archivo bundleado en addons/erpec_fiscal_native/
reference/Catalogo_ATS_2026.xls y el esquema en addons/erpec_fiscal_native/
xsd/at.xsd son la descarga del 23-09-2026 desde
https://www.sri.gob.ec/formularios-e-instructivos1 (sección Anexo
Transaccional Simplificado); su huella se verifica en ats_catalog_seal.py.
No se completan tramos no verificados (tablas de retenciones históricas,
esquema RIMPE, reembolso de gastos, clave primaria): quedan fuera de alcance
hasta que exista una necesidad real de consumirlos.

Este catálogo habilita el mapeo de tpIdProv/tpIdCliente, tipoComprobante y
codSustento exigidos por ats.xsd. No genera por sí solo el XML del ATS: la
generación de las secciones de compras, ventas y anulados requiere además una
clasificación explícita del sustento tributario por documento (ver
addons/erpec_workspace/tax_intersection.py para compras, ya implementado; para
ventas/notas/anulados/reembolsos no existe todavía — ver docs/ALCANCE_ATS_RDEP.md).
"""

# Tabla 1: PERÍODO - MES
MONTHS = {
    '01': 'Enero', '02': 'Febrero', '03': 'Marzo', '04': 'Abril', '05': 'Mayo',
    '06': 'Junio / I Semestre (régimen RIMPE)', '07': 'Julio', '08': 'Agosto',
    '09': 'Septiembre', '10': 'Octubre', '11': 'Noviembre',
    '12': 'Diciembre / II Semestre (régimen RIMPE)',
}

# Tabla 2: código a usar → tipo de transacción + tipo de identificación (tpIdProv/tpIdCliente)
IDENTIFICATION_CODES = {
    '01': {'transaction': 'COMPRA', 'identification': 'RUC'},
    '02': {'transaction': 'COMPRA', 'identification': 'CEDULA'},
    '03': {'transaction': 'COMPRA', 'identification': 'PASAPORTE / IDENTIFICACIÓN TRIBUTARIA DEL EXTERIOR'},
    '04': {'transaction': 'VENTA', 'identification': 'RUC'},
    '05': {'transaction': 'VENTA', 'identification': 'CEDULA'},
    '06': {'transaction': 'VENTA', 'identification': 'PASAPORTE / IDENTIFICACIÓN TRIBUTARIA DEL EXTERIOR'},
    '07': {'transaction': 'VENTA', 'identification': 'CONSUMIDOR FINAL'},
    '09': {'transaction': 'EXPORTACION', 'identification': '-'},
    '10': {'transaction': 'TARJETA DE CREDITO', 'identification': 'RUC'},
    '11': {'transaction': 'TARJETA DE CREDITO', 'identification': 'PASAPORTE / IDENTIFICACIÓN TRIBUTARIA DEL EXTERIOR'},
    '12': {'transaction': 'RENDIMIENTOS FINANCIEROS', 'identification': 'RUC'},
    '13': {'transaction': 'RENDIMIENTOS FINANCIEROS', 'identification': 'CEDULA'},
    '14': {'transaction': 'RENDIMIENTOS FINANCIEROS', 'identification': 'PASAPORTE / IDENTIFICACIÓN TRIBUTARIA DEL EXTERIOR'},
    '15': {'transaction': 'FONDOS Y FIDEICOMISOS', 'identification': 'RUC'},
    '16': {'transaction': 'FONDOS Y FIDEICOMISOS', 'identification': 'CEDULA'},
    '17': {'transaction': 'FONDOS Y FIDEICOMISOS', 'identification': 'PASAPORTE / IDENTIFICACIÓN TRIBUTARIA DEL EXTERIOR'},
    '18': {'transaction': 'COMPROBANTES ANULADOS', 'identification': '-'},
    '19': {'transaction': 'VENTA', 'identification': 'PLACA o RAMV/CPN'},
    '20': {'transaction': 'EXPORTACION', 'identification': 'RUC'},
    '21': {'transaction': 'EXPORTACION', 'identification': 'PASAPORTE / IDENTIFICACIÓN TRIBUTARIA DEL EXTERIOR'},
}

# Tabla 4: TIPOS COMPROBANTES AUTORIZADOS (código → descripción, sustentos válidos)
VOUCHER_TYPES = {
    '1': {'name': 'Factura', 'validSustento': ['01', '02', '03', '04', '05', '06', '07', '08', '09', '14', '15', '00']},
    '2': {'name': 'Nota o boleta de venta', 'validSustento': ['02', '04', '05', '07', '08', '14', '15', '00']},
    '3': {'name': 'Liquidación de compra de Bienes o Prestación de servicios', 'validSustento': ['01', '02', '03', '04', '05', '06', '07', '08', '14', '15']},
    '4': {'name': 'Nota de crédito', 'validSustento': ['01', '02', '03', '04', '05', '06', '07', '08', '09', '14', '15', '00']},
    '5': {'name': 'Nota de débito', 'validSustento': ['01', '02', '03', '04', '05', '06', '07', '08', '09', '14', '15', '00']},
    '6': {'name': 'Guías de Remisión', 'validSustento': []},
    '7': {'name': 'Comprobante de Retención', 'validSustento': []},
    '8': {'name': 'Boletos o entradas a espectáculos públicos', 'validSustento': []},
    '9': {'name': 'Tiquetes o vales emitidos por máquinas registradoras', 'validSustento': ['02']},
    '11': {'name': 'Pasajes expedidos por empresas de aviación', 'validSustento': ['01', '02', '05']},
    '12': {'name': 'Documentos emitidos por instituciones financieras', 'validSustento': ['01', '02', '11', '15']},
    '15': {'name': 'Comprobante de venta emitido en el Exterior', 'validSustento': ['02', '04', '05', '07', '15']},
    '16': {'name': 'Formulario Único de Exportación (FUE) o Declaración Aduanera Única (DAU) o Declaración Andina de Valor (DAV)', 'validSustento': []},
    '18': {'name': 'Documentos autorizados utilizados en ventas excepto N/C N/D', 'validSustento': []},
    '19': {'name': 'Comprobantes de Pago de Cuotas o Aportes', 'validSustento': ['02', '10', '13', '00']},
    '20': {'name': 'Documentos por Servicios Administrativos emitidos por Inst. del Estado', 'validSustento': ['02']},
    '21': {'name': 'Carta de Porte Aérea', 'validSustento': ['01', '02', '08']},
    '22': {'name': 'RECAP', 'validSustento': []},
    '23': {'name': 'Nota de Crédito TC', 'validSustento': []},
    '24': {'name': 'Nota de Débito TC', 'validSustento': []},
    '41': {'name': 'Comprobante de venta emitido por reembolso', 'validSustento': ['01', '02', '03', '04', '05', '06', '07']},
    '42': {'name': 'Documento retención presuntiva y retención emitida por propio vendedor o por intermediario', 'validSustento': ['00', '12']},
    '43': {'name': 'Liquidación para Explotación y Exploración de Hidrocarburos', 'validSustento': ['01', '02', '06', '07']},
    '44': {'name': 'Comprobante de Contribuciones y Aportes', 'validSustento': []},
    '45': {'name': 'Liquidación por reclamos de aseguradoras', 'validSustento': ['09']},
    '47': {'name': 'Nota de Crédito por Reembolso Emitida por Intermediario', 'validSustento': ['01', '02', '03', '04', '06', '07']},
    '48': {'name': 'Nota de Débito por Reembolso Emitida por Intermediario', 'validSustento': ['01', '02', '03', '04', '06', '07']},
    '49': {'name': 'Proveedor Directo de Exportador Bajo Régimen Especial', 'validSustento': []},
    '50': {'name': 'A Inst. Estado y Empr. Públicas que percibe ingreso exento de Imp. Renta', 'validSustento': []},
    '51': {'name': 'N/C A Inst. Estado y Empr. Públicas que percibe ingreso exento de Imp. Renta', 'validSustento': []},
    '52': {'name': 'N/D A Inst. Estado y Empr. Públicas que percibe ingreso exento de Imp. Renta', 'validSustento': []},
    '294': {'name': 'Liquidación de compra de Bienes Muebles Usados', 'validSustento': ['01', '02', '03', '04', '05', '06', '07', '08']},
    '344': {'name': 'Liquidación de compra de vehículos usados', 'validSustento': ['01', '02', '03', '04', '05', '06', '07', '08']},
    '364': {'name': 'Acta Entrega-Recepción PET', 'validSustento': ['02', '07']},
    '370': {'name': 'Factura operadora transporte / socio', 'validSustento': []},
    '371': {'name': 'Comprobante socio a operadora de transporte', 'validSustento': []},
    '372': {'name': 'Nota de crédito operadora transporte / socio', 'validSustento': []},
    '373': {'name': 'Nota de débito operadora transporte / socio', 'validSustento': []},
    '374': {'name': 'Nota de débito operadora transporte / socio', 'validSustento': []},
    '375': {'name': 'Liquidación de compra RISE de bienes o prestación de servicios', 'validSustento': ['01', '02', '03', '04', '05', '06', '07', '08']},
}

# Tabla 5: SUSTENTO DEL COMPROBANTE (código → tipo de sustento, tipos de comprobante válidos)
SUPPORT_CODES = {
    '01': {'name': 'Crédito Tributario para declaración de IVA (servicios y bienes distintos de inventarios y activos fijos)', 'validVoucherTypes': ['1', '3', '4', '5', '11', '12', '21', '41', '43', '47', '48', '294', '344']},
    '02': {'name': 'Costo o Gasto para declaración de IR (servicios y bienes distintos de inventarios y activos fijos)', 'validVoucherTypes': ['1', '2', '3', '4', '5', '9', '11', '12', '15', '19', '20', '21', '41', '43', '47', '48', '294', '344', '364']},
    '03': {'name': 'Activo Fijo - Crédito Tributario para declaración de IVA', 'validVoucherTypes': ['1', '3', '4', '5', '41', '47', '48', '294', '344']},
    '04': {'name': 'Activo Fijo - Costo o Gasto para declaración de IR', 'validVoucherTypes': ['1', '2', '3', '4', '5', '15', '41', '47', '48', '294', '344']},
    '05': {'name': 'Liquidación Gastos de Viaje, hospedaje y alimentación Gastos IR (a nombre de empleados y no de la empresa)', 'validVoucherTypes': ['1', '2', '3', '4', '5', '11', '15', '41', '294', '344']},
    '06': {'name': 'Inventario - Crédito Tributario para declaración de IVA', 'validVoucherTypes': ['1', '3', '4', '5', '41', '43', '47', '48', '294', '344']},
    '07': {'name': 'Inventario - Costo o Gasto para declaración de IR', 'validVoucherTypes': ['1', '2', '3', '4', '5', '15', '41', '43', '47', '48', '294', '344', '364']},
    '08': {'name': 'Valor pagado para solicitar Reembolso de Gasto (intermediario)', 'validVoucherTypes': ['1', '2', '3', '4', '5', '21', '294', '344']},
    '09': {'name': 'Reembolso por Siniestros', 'validVoucherTypes': ['1', '4', '5', '45']},
    '10': {'name': 'Distribución de Dividendos, Beneficios o Utilidades', 'validVoucherTypes': ['19']},
    '11': {'name': "Convenios de débito o recaudación para IFI's", 'validVoucherTypes': ['12']},
    '12': {'name': 'Impuestos y retenciones presuntivos', 'validVoucherTypes': ['42']},
    '13': {'name': 'Valores reconocidos por entidades del sector público a favor de sujetos pasivos', 'validVoucherTypes': ['19']},
    '14': {'name': 'Valores facturados por socios a operadoras de transporte (que no constituyen gasto de dicha operadora)', 'validVoucherTypes': ['1', '2', '3', '4', '5']},
    '15': {'name': 'Pagos efectuados por consumos propios y de terceros de servicios digitales', 'validVoucherTypes': ['1', '2', '3', '4', '5', '12', '15']},
    '00': {'name': 'Casos especiales cuyo sustento no aplica en las opciones anteriores', 'validVoucherTypes': ['1', '2', '4', '5', '19', '42']},
}

# Tabla de países (país de residencia/pago), misma hoja del archivo oficial (Tabla 16: PAÍSES).
# BELARUS (241) y BIELORRUSIA (596) son dos códigos distintos para el mismo país en el archivo
# oficial; se transcriben ambos tal cual, sin corregir lo que el SRI publica.
COUNTRY_CODES = {
    '016': 'AMERICAN SAMOA',
    '052': 'PRINCIPADO DEL VALLE DE ANDORRA',
    '074': 'BOUVET ISLAND',
    '101': 'ARGENTINA',
    '102': 'BOLIVIA',
    '103': 'BRASIL',
    '104': 'CANADA',
    '105': 'COLOMBIA',
    '106': 'COSTA RICA',
    '107': 'CUBA',
    '108': 'CHILE',
    '109': 'ANGUILA',
    '110': 'ESTADOS UNIDOS',
    '111': 'GUATEMALA',
    '112': 'HAITI',
    '113': 'HONDURAS',
    '114': 'JAMAICA',
    '115': 'MALVINAS  ISLAS',
    '116': 'MEXICO',
    '117': 'NICARAGUA',
    '118': 'PANAMA',
    '119': 'PARAGUAY',
    '120': 'PERU',
    '121': 'PUERTO RICO',
    '122': 'REPUBLICA DOMINICANA',
    '123': 'EL SALVADOR',
    '124': 'TRINIDAD Y TOBAGO',
    '125': 'URUGUAY',
    '126': 'VENEZUELA',
    '127': 'CURAZAO',
    '129': 'BAHAMAS',
    '130': 'BARBADOS',
    '131': 'GRANADA',
    '132': 'GUYANA',
    '133': 'SURINAM',
    '134': 'ANTIGUA Y BARBUDA',
    '135': 'BELICE',
    '136': 'DOMINICA',
    '137': 'SAN CRISTOBAL Y NEVIS',
    '138': 'SANTA LUCIA',
    '139': 'SAN VICENTE Y LAS GRANAD.',
    '140': 'ANTILLAS HOLANDESAS',
    '141': 'ARUBA',
    '142': 'BERMUDA',
    '143': 'GUADALUPE',
    '144': 'GUYANA FRANCESA',
    '145': 'ISLAS CAIMAN',
    '146': 'ISLAS VIRGENES (BRITANICAS)',
    '147': 'JOHNSTON ISLA',
    '148': 'MARTINICA',
    '149': 'MONTSERRAT ISLA',
    '151': 'TURCAS  Y CAICOS ISLAS',
    '152': 'VIRGENES,ISLAS(NORT.AMER.)',
    '201': 'ALBANIA',
    '202': 'ALEMANIA',
    '203': 'AUSTRIA',
    '204': 'BELGICA',
    '205': 'BULGARIA',
    '207': 'ALBORAN Y PEREJIL',
    '208': 'DINAMARCA',
    '209': 'ESPAÑA',
    '211': 'FRANCIA',
    '212': 'FINLANDIA',
    '213': 'REINO UNIDO',
    '214': 'GRECIA',
    '215': 'PAISES BAJOS (HOLANDA)',
    '216': 'HUNGRIA',
    '217': 'IRLANDA',
    '218': 'ISLANDIA',
    '219': 'ITALIA',
    '220': 'LUXEMBURGO',
    '221': 'MALTA',
    '222': 'NORUEGA',
    '223': 'POLONIA',
    '224': 'PORTUGAL',
    '225': 'RUMANIA',
    '226': 'SUECIA',
    '227': 'SUIZA',
    '228': 'CANARIAS  ISLAS',
    '229': 'UCRANIA',
    '230': 'RUSIA',
    '231': 'YUGOSLAVIA',
    '233': 'ANDORRA',
    '234': 'LIECHTENSTEIN',
    '235': 'MONACO',
    '237': 'SAN MARINO',
    '238': 'VATICANO (SANTA SEDE)',
    '239': 'GIBRALTAR',
    '241': 'BELARUS',
    '242': 'BOSNIA Y HERZEGOVINA',
    '243': 'CROACIA',
    '244': 'ESLOVENIA',
    '245': 'ESTONIA',
    '246': 'GEORGIA',
    '247': 'GROENLANDIA',
    '248': 'LETONIA',
    '249': 'LITUANIA',
    '250': 'MOLDOVA',
    '251': 'MACEDONIA',
    '252': 'ESLOVAQUIA',
    '253': 'ISLAS FAROE',
    '260': 'FRENCH SOUTHERN TERRITORIES',
    '301': 'AFGANISTAN',
    '302': 'ARABIA SAUDITA',
    '303': 'MYANMAR (BURMA)',
    '304': 'CAMBOYA',
    '306': 'COREA NORTE',
    '307': 'TAIWAN (CHINA)',
    '308': 'FILIPINAS',
    '309': 'INDIA',
    '310': 'INDONESIA',
    '311': 'IRAK',
    '312': 'IRAN (REPUBLICA ISLAMICA)',
    '313': 'ISRAEL',
    '314': 'JAPON',
    '315': 'JORDANIA',
    '316': 'KUWAIT',
    '317': 'LAOS, REP. POP. DEMOC.',
    '318': 'LIBANO',
    '319': 'MALASIA',
    '321': 'MONGOLIA (MANCHURIA)',
    '322': 'PAKISTAN',
    '323': 'SIRIA',
    '325': 'TAILANDIA',
    '327': 'BAHREIN',
    '328': 'BANGLADESH',
    '329': 'BUTAN',
    '330': 'COREA DEL SUR',
    '331': 'CHINA POPULAR',
    '332': 'CHIPRE',
    '333': 'EMIRATOS ARABES UNIDOS',
    '334': 'QATAR',
    '335': 'MALDIVAS',
    '336': 'NEPAL',
    '337': 'OMAN',
    '338': 'SINGAPUR',
    '339': 'SRI LANKA (CEILAN)',
    '341': 'VIETNAM',
    '342': 'YEMEN',
    '343': 'ISLAS HEARD Y MCDONALD',
    '344': 'BRUNEI DARUSSALAM',
    '346': 'TURQUIA',
    '347': 'AZERBAIJAN',
    '348': 'KAZAJSTAN',
    '349': 'KIRGUIZISTAN',
    '350': 'TAJIKISTAN',
    '351': 'TURKMENISTAN',
    '352': 'UZBEKISTAN',
    '353': 'PALESTINA',
    '354': 'HONG KONG',
    '355': 'MACAO',
    '356': 'ARMENIA',
    '382': 'MONTENEGRO',
    '402': 'BURKINA FASO',
    '403': 'ARGELIA',
    '404': 'BURUNDI',
    '405': 'CAMERUN',
    '406': 'CONGO',
    '407': 'ETIOPIA',
    '408': 'GAMBIA',
    '409': 'GUINEA',
    '410': 'LIBERIA',
    '412': 'MADAGASCAR',
    '413': 'MALAWI',
    '414': 'MALI',
    '415': 'MARRUECOS',
    '416': 'MAURITANIA',
    '417': 'NIGERIA',
    '419': 'ZIMBABWE (RHODESIA)',
    '420': 'SENEGAL',
    '421': 'SUDAN',
    '422': 'SUDAFRICA  (CISKEI)',
    '423': 'SIERRA LEONA',
    '425': 'TANZANIA',
    '426': 'UGANDA',
    '427': 'ZAMBIA',
    '428': 'ÅLAND ISLANDS',
    '429': 'BENIN',
    '430': 'BOTSWANA',
    '431': 'REPUBLICA CENTROAFRICANA',
    '432': 'COSTA DE MARFIL',
    '433': 'CHAD',
    '434': 'EGIPTO',
    '435': 'GABON',
    '436': 'GHANA',
    '437': 'GUINEA-BISSAU',
    '438': 'GUINEA ECUATORIAL',
    '439': 'KENIA',
    '440': 'LESOTHO',
    '441': 'MAURICIO',
    '442': 'MOZAMBIQUE',
    '443': 'MAYOTTE',
    '444': 'NIGER',
    '445': 'RWANDA',
    '446': 'SEYCHELLES',
    '447': 'SAHARA OCCIDENTAL',
    '448': 'SOMALIA',
    '449': 'SANTO TOME Y PRINCIPE',
    '450': 'SWAZILANDIA',
    '451': 'TOGO',
    '452': 'TUNEZ',
    '453': 'ZAIRE',
    '454': 'ANGOLA',
    '456': 'CABO VERDE',
    '458': 'COMORAS',
    '459': 'DJIBOUTI',
    '460': 'NAMIBIA',
    '463': 'ERITREA',
    '464': 'MOROCCO',
    '465': 'REUNION',
    '466': 'SANTA ELENA',
    '499': 'JERSEY',
    '501': 'AUSTRALIA',
    '503': 'NUEVA ZELANDA',
    '504': 'SAMOA OCCIDENTAL',
    '506': 'FIJI',
    '507': 'PAPUA NUEVA GUINEA',
    '508': 'TONGA',
    '509': 'PALAO  (BELAU)  ISLAS',
    '510': 'KIRIBATI',
    '511': 'MARSHALL ISLAS',
    '512': 'MICRONESIA',
    '513': 'NAURU',
    '514': 'SALOMON  ISLAS',
    '515': 'TUVALU',
    '516': 'VANUATU',
    '517': 'GUAM',
    '518': 'ISLAS COCOS (KEELING)',
    '519': 'ISLAS COOK',
    '520': 'ISLAS NAVIDAD',
    '521': 'MIDWAY ISLAS',
    '522': 'NIUE ISLA',
    '523': 'NORFOLK ISLA',
    '524': 'NUEVA  CALEDONIA',
    '525': 'PITCAIRN, ISLA',
    '526': 'POLINESIA FRANCESA',
    '529': 'TIMOR DEL ESTE',
    '530': 'Tokelau',
    '531': 'WAKE ISLA',
    '532': 'WALLIS Y FUTUNA, ISLAS',
    '534': 'SINT MAARTEN (DUTCH PART)',
    '590': 'SAINT BARTHELEMY',
    '593': 'ECUADOR',
    '594': 'AGUAS INTERNACIONALES',
    '595': 'ALTO VOLTA',
    '596': 'BIELORRUSIA',
    '597': 'COTE DÍVOIRE',
    '598': 'CYPRUS',
    '599': 'REPUBLICA CHECA',
    '600': 'FALKLAND ISLANDS',
    '601': 'LATVIA',
    '602': 'LIBIA',
    '603': 'NORTHERN MARIANA ISL',
    '604': 'ST. PIERRE AND MIQUE',
    '605': 'SYRIAN ARAB REPUBLIC',
    '606': 'TERRITORIO ANTARTICO BRITANICO',
    '607': 'TERRITORIO BRITANICO OCEANO IN',
    '688': 'SERBIA',
    '831': 'GUERNSEY',
    '833': 'ISLE OF MAN',
}

SOURCE = {
    'file': 'Catálogo Anexo Transaccional Simplificado ATS.xls',
    'sheet': 'TABLAS REFERENCIALES',
    'downloadedAt': '2026-09-23',
    'listedUpdate': '2026-08-06',
    'url': 'https://www.sri.gob.ec/formularios-e-instructivos1',
    'previousDownload': {'downloadedAt': '2026-09-13', 'listedUpdate': '2026-03-03'},
    'bundled': 'addons/erpec_fiscal_native/reference/Catalogo_ATS_2026.xls',
    'schema': 'addons/erpec_fiscal_native/xsd/at.xsd',
    'schemaUrl': 'https://descargas.sri.gob.ec/download/anexos/ats/ats.xsd',
}
