from . import test_payroll
from . import test_annex_rdep
from . import test_legal_parameters
from . import test_reports
from . import test_payslip_email
from . import test_opening_balance
from . import test_mail_server_env
from . import test_benefits_advances
from . import test_move_copy
